### ISSUE TITLE
Cannot create database

### ISSUE THREAD

**Issue by msmirle** [md100play/AudioDidact#97]
Hi Mike!

Love this software but when I built this on my Ubuntu 18.04 system in a container it was throwing an error that the database could not be created.

I installed using docker compose by executing this command after downloading the unmodified docker-compose.yml file:
docker-compose -f ~/docker/docker-compose.yml up -d

I'm admittedly new at all this so please tell me if I'm missing something!

**Comment by MikeDombo** [comment]
Can you please try updating the version of mysql in the docker compose file to version 8. This should look like

```
mysql:
    image: 'mysql:8'
```

**Comment by msmirle** [comment]
That was fast! Tried it and got this:

ERROR: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client
Fatal error: Uncaught PDOException: PDO::__construct(): The server requested authentication method unknown to the client [caching_sha2_password] in /var/www/html/classes/DB/MySQLDAL.php:78 Stack trace: #0 /var/www/html/classes/DB/MySQLDAL.php(78): PDO->__construct('mysql:host=mysq...', 'root', 'password') #1 /var/www/html/classes/GlobalFunctions.php(237): AudioDidact\DB\MySQLDAL->__construct('mysql:host=mysq...') #2 /var/www/html/header.php(64): AudioDidact\GlobalFunctions::getDAL() #3 /var/www/html/index.php(3): require_once('/var/www/html/h...') #4 {main} Next PDOException: SQLSTATE[HY000] [2054] The server requested authentication method unknown to the client in /var/www/html/classes/DB/MySQLDAL.php:78 Stack trace: #0 /var/www/html/classes/DB/MySQLDAL.php(78): PDO->__construct('mysql:host=mysq...', 'root', 'password') #1 /var/www/html/classes/GlobalFunctions.php(237): AudioDidact\DB\MySQLDAL->__construct('mysql:host=mysq...') #2 /var/www/html/header.php(64): AudioDidact\GlobalFunctions::getDAL() #3 /var/www/html/index in /var/www/html/classes/DB/MySQLDAL.php on line 78

**Comment by MikeDombo** [comment]
Looks like they updated the default authentication. Please change it now to

```
mysql:
    image: 'mysql:8'
    command: --default-authentication-plugin=mysql_native_password
    ... rest of the config ...
```

**Comment by msmirle** [comment]
First of all thanks for the help here!

The page loads now and I get this at the top of the first page on the site:

**"The database needs to be created, this will be completed automatically..."**

Attached are the logs that I see for each container:
[mysql log.txt](https://github.com/MikeDombo/AudioDidact/files/3699718/mysql.log.txt)
[audiodidact log.txt](https://github.com/MikeDombo/AudioDidact/files/3699719/audiodidact.log.txt)

**Comment by MikeDombo** [comment]
Does it put that up every time you load the page? It should only show up the first time.

**Comment by msmirle** [comment]
Every time I load up the page.

**Comment by MikeDombo** [comment]
Ok no problem. I just made a change which I'm fairly sure will fix the issue. Docker will rebuild shortly and then if you run docker compose again it should pull down the latest version. If not, you can add `--pull` to the command and that should get docker compose to look for an update.

**Comment by MikeDombo** [comment]
The new build is now available.

**Comment by msmirle** [comment]
Ok I tried it but not sure if I'm using the pull command correctly. I did this:
**docker-compose pull
docker-compose -f ~/docker/docker-compose.yml up -d**

It didn't work. Same error as before. So I rolled back the VM to a state before I started installing and just ran the regular docker-compose command:
**docker-compose -f ~/docker/docker-compose.yml up -d**

Still same problem. Thanks again for helping. :) New Logs attached
[Audiodidact.txt](https://github.com/MikeDombo/AudioDidact/files/3700307/Audiodidact.txt)
[mysql.txt](https://github.com/MikeDombo/AudioDidact/files/3700308/mysql.txt)

**Comment by MikeDombo** [comment]
I'll try on my computer shortly, but I'd try going back to mysql 5.7.

**Comment by msmirle** [comment]
Ok went back to mysql 5.7 and the new build appears to be working!

The only issue now is that my RSS feed doesn't seem to be updating when I upload content. However, I can see and play files it under 'Feed Items' on the user page. So whatever updates the RSS feed doesn't seem to be working.

So close!!

**Comment by MikeDombo** [comment]
OK good. The RSS feed is automatically updated when you add any videos. If adding any of them fails then it will not update the feed. So I don't know why it wouldn't be updated if you can see it on the site. Are you checking the feed yourself, or using podcast app? If you just load the XML yourself it should definitely be up to date, but if you're using an app then many of them cache for quite a while before they will actually update again.

**Comment by msmirle** [comment]
Yeah it's weird. I can see files on my account page and play them just fine.

However, the feed file just looks like this:

<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" xmlns:sy="http://purl.org/rss/1.0/modules/syndication/" version="2.0">
<channel>
<title>AudioDidact</title>
<link>http://192.168.200.59/</link>
<description>
<![CDATA[
Learn by putting audio and video from multiple sources into a portable podcast feed.
]]>
</description>
<image>
<title>AudioDidact</title>
<link>http://192.168.200.59/</link>
<url>
http://192.168.200.59/public/img/favicon/favicon-512x512.png
</url>
</image>
<lastBuildDate>Tue, 08 Oct 2019 03:15:23 +0000</lastBuildDate>
<pubDate>Tue, 08 Oct 2019 03:15:23 +0000</pubDate>
<atom:link href="http://192.168.200.59/user/michael/feed/" rel="self" type="application/rss+xml"/>
<itunes:image href="http://192.168.200.59/public/img/favicon/favicon-512x512.png"/>
<itunes:author>Michael Dombrowski</itunes:author>
<itunes:category text="Technology"/>
<language>en-US</language>
<itunes:explicit>yes</itunes:explicit>
<sy:updatePeriod>hourly</sy:updatePeriod>
<sy:updateFrequency>1</sy:updateFrequency>
<ttl>15</ttl>
</channel>
</rss>



________________________________

**Comment by MikeDombo** [comment]
And have you tried putting yet another thing into the feed? That should cause it to be generated again. There is no other way to generate the feed except to put something into it.

**Comment by MikeDombo** [comment]
The text of the feed is stored in the database, so if there's something wrong with the connection to the database then it won't be able to update it. You may want to check the audiodidact log again to see if there are any errors.

**Comment by msmirle** [comment]
Ok I'll look at it again tonight and report back!

**Comment by msmirle** [comment]
Ok so I quickly built a Ubuntu server in Azure with docker and was able to install everything just fine, including having a successfully updated RSS feed.
Then on my home Ubuntu Server (on Hyper-V) I did the same thing and still have the problem of the RSS feed not updating.
One thing that I noticed is that in the working version, I see a message of "Successfully Uploaded!" in the progress bar when I upload a file. 
If I replicate the same upload on my non-working server, it just sits at 100% and I never see the "Successfully Uploaded!" message.
